### ISSUE TITLE
ppc/ppc64 assembler and linker problems for Xcode 5.0.2

### ISSUE THREAD

**Issue by inspector-g** [devernay/xcodelegacy#1]
Your shell script works great! However, I found a few issues regarding Xcode 5.0.2 and ppc/ppc64 support (I have no idea if these issues are present in Xcode 5.0.0 and 5.0.1).

When attempting to build a project for ppc/ppc64, Xcode 5.0.2 cannot find the correct `as` command. Also, the `ld` binary within Xcode.app refuses to link ppc/ppc64 architectures.

I have forked your repo and committed some changes to resolve these issues. Please take a look and merge them in, if you find them acceptable! I did not go so far as to check the version of Xcode before performing the necessary operations to fix the problem for 5.0.2 (all the machines I am personally concerned about are running 5.0.2), so you might want to add a couple checks for &lt;5 and &gt;=5 if you choose to apply my patch.

Thanks!

**Comment by devernay** [comment]
Merged  https://github.com/devernay/xcodelegacy/pull/2
