### ISSUE TITLE
installing errors

### ISSUE THREAD

**Issue by Gnimuc** [devernay/xcodelegacy#10]
hi devernay,
when I run 'sudo sh XcodeLegacy.sh install', several errors happened. 
I want to use 10.7 SDK, what should I do? plz help me 
here is the information:

Last login: Sun Jan 18 21:33:23 on ttys000
gnimucs-mini:~ Zero$ cd downloads/xcodelegacy-master/
gnimucs-mini:xcodelegacy-master Zero$ ls
README.md			xcode_3.2.6_and_ios_sdk_4.3.dmg
XcodeLegacy.sh
gnimucs-mini:xcodelegacy-master Zero$ sudo sh XcodeLegacy.sh install
Password:
Info: found Xcode >= 4.3
gzip: can't stat: XcodePluginGCC40.tar.gz (XcodePluginGCC40.tar.gz.gz): No such file or directory
installed XcodePluginGCC40.tar.gz
gzip: can't stat: XcodePluginGCC42.tar.gz (XcodePluginGCC42.tar.gz.gz): No such file or directory
installed XcodePluginGCC42.tar.gz
gzip: can't stat: XcodePluginLLVMGCC42.tar.gz (XcodePluginLLVMGCC42.tar.gz.gz): No such file or directory
installed XcodePluginLLVMGCC42.tar.gz
gzip: can't stat: XcodePPCas.tar.gz (XcodePPCas.tar.gz.gz): No such file or directory
installed XcodePPCas.tar.gz
gzip: can't stat: Xcode3ld.tar.gz (Xcode3ld.tar.gz.gz): No such file or directory
cp: directory /Applications/Xcode.app/Contents/Developer/usr/libexec/gcc/darwin/ppc does not exist
cp: directory /Applications/Xcode.app/Contents/Developer/usr/libexec/gcc/darwin/ppc64 does not exist
installed Xcode3ld.tar.gz
gzip: can't stat: Xcode104SDK.tar.gz (Xcode104SDK.tar.gz.gz): No such file or directory
installed Xcode104SDK.tar.gz
touch: /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.4u.sdk/legacy: No such file or directory
gzip: can't stat: Xcode105SDK.tar.gz (Xcode105SDK.tar.gz.gz): No such file or directory
installed Xcode105SDK.tar.gz
touch: /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.5.sdk/legacy: No such file or directory
gzip: can't stat: Xcode106SDK.tar.gz (Xcode106SDK.tar.gz.gz): No such file or directory
installed Xcode106SDK.tar.gz
touch: /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.6.sdk/legacy: No such file or directory
gzip: can't stat: Xcode107SDK.tar.gz (Xcode107SDK.tar.gz.gz): No such file or directory
installed Xcode107SDK.tar.gz
touch: /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.7.sdk/legacy: No such file or directory
gzip: can't stat: Xcode108SDK.tar.gz (Xcode108SDK.tar.gz.gz): No such file or directory
installed Xcode108SDK.tar.gz
touch: /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.8.sdk/legacy: No such file or directory
Installing GCC 4.0
installer: Error the package path specified was invalid: 'xcode_3.2.6_gcc4.0.pkg'.
Installing GCC 4.2
installer: Error the package path specified was invalid: 'xcode_3.2.6_gcc4.2.pkg'.
Installing LLVM GCC 4.2
installer: Error the package path specified was invalid: 'xcode_3.2.6_llvm-gcc4.2.pkg'.

**Comment by devernay** [comment]
maybe read the doc? :-)

Typically, you will want to run this script with the buildpackages argument first, then the install argument, 
and lastly the cleanpackages argument, in order to properly install the legacy Xcode files.
The install and uninstall phases have to be run with administrative rights, as in:
 $ sudo ./XcodeLegacy.sh install

**Comment by Gnimuc** [comment]
Thank you devernay, I missed a downlaod message generated by the buildpackages argument. Now everything works. :)
