### ISSUE TITLE
Xcode 7 (beta) support

### ISSUE THREAD

**Issue by nbeadman** [devernay/xcodelegacy#11]
Has anyone looked at supporting Xcode 7 yet? With Xcode 6.4 not being supported on OS X 10.11 El Cap the lack of XcodeLegacy will be a serious impediment to my using El Cap.

Also, I want to say thanks for this. Great work.

**Comment by devernay** [comment]
It's probably not a big deal, but I'll only look at it when I upgrade

**Comment by devernay** [comment]
Any Xcode 7 user around to point out what's removed in Xcode 7 that was in 6.4?

**Comment by TaleTN** [comment]
I just wanted to add that XcodeLegacy seems to work fine with Xcode 7.0.1 on Mac OS X 10.10.5.

**Comment by devernay** [comment]
And it now also supports OS X 10.11 (see https://github.com/devernay/xcodelegacy/issues/16)
