### ISSUE TITLE
OSX 10.11: installing compilers (GCC 4.0, GCC 4.2, LLVM-GCC 4.2) fail

### ISSUE THREAD

**Issue by devernay** [devernay/xcodelegacy#16]
Can anyone help?
```
*** Installing GCC 4.0
installer: Package name is xcode_3.2.6_gcc4.0
installer: Installing at base path /
installer: The install failed (Le programme d’installation a rencontré une erreur qui a provoqué l’échec de l’installation. Contactez l’éditeur du logiciel pour obtenir de l’aide.)
*** Installing GCC 4.2
installer: Package name is xcode_3.2.6_gcc4.2
installer: Installing at base path /
installer: The install failed (Le programme d’installation a rencontré une erreur qui a provoqué l’échec de l’installation. Contactez l’éditeur du logiciel pour obtenir de l’aide.)
*** Installing LLVM GCC 4.2
installer: Package name is xcode_3.2.6_llvm-gcc4.2
installer: Installing at base path /
installer: The install failed (Le programme d’installation a rencontré une erreur qui a provoqué l’échec de l’installation. Contactez l’éditeur du logiciel pour obtenir de l’aide.)
```

**Comment by alexey-lysiuk** [comment]
I didn't try by myself yet, but these errors can be caused by the ['rootless'](http://apple.stackexchange.com/questions/193368/what-is-the-rootless-feature-in-el-capitan-really) feature.
If so, nothing can be done with it, except to disable 'rootless'.

**Comment by devernay** [comment]
I'll use the same install method as other packages, it should work

**Comment by alexey-lysiuk** [comment]
It's impossible to write to `/usr` directory (with exception of `/usr/local`) on El Capitan with 'rootless' enabled, and it is enabled by default.
Only Apple-signed packages can do this.

**Comment by devernay** [comment]
I could install in /Applications/Xcode.app//Contents/Developer/Toolchains/XcodeDefault.xctoolchain and put links in /usr/local (which is not protected by sandbox)

**Comment by devernay** [comment]
fixed by https://github.com/devernay/xcodelegacy/commit/10f767015a51935d9cdfb532c2438fec93a161fb please test.
