### ISSUE TITLE
gcc error

### ISSUE THREAD

**Issue by dfroger** [devernay/xcodelegacy#19]
Hello,

I'm using a fresh Maverics Vagrant box provided [here](https://github.com/AndrewDryga/vagrant-box-osx).

I use the script from the Git repository (last commit Sep 7, 2015).

Install works:

    ./XcodeLegacy.sh buildpackages
    sudo ./XcodeLegacy.sh install

But when I try to invoke `gcc`, I get the error:

    gcc: error: can't exec '/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/libexec/gcc' (errno=Permission denied)

**Comment by dfroger** [comment]
Note: Version 1.2 of XcodeLegacy.sh works.

**Comment by devernay** [comment]
I'll try to download your box and test.
In the mean time, can you please give the output of:
```
type -a gcc
type -a gcc-4.2
ls -l /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/libexec/gcc
```

**Comment by dfroger** [comment]
Sorry for the late reply... I just try again with c5ca493b063b18762635bdc7ae559b5194157c77, the error message is the same.

    $ type -a gcc
    gcc is /usr/bin/gcc

    $ type -a gcc-4.2
    gcc-4.2 is /usr/bin/gcc-4.2

    $ ls -l /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/libexec/gcc
    total 0
    drwxr-xr-x  4 vagrant  wheel  136 Nov 10 03:57 i686-apple-darwin10
    drwxr-xr-x  4 vagrant  wheel  136 Nov 10 03:57 powerpc-apple-darwin10

**Comment by devernay** [comment]
I get the same here.
I don't know what that "gcc" in /usr/bin does. Anybody has an idea?
My guess is that it looks for an executable file called "gcc" in /Applications/Xcode.app/Contents/Developer, and this file happens to be a directory (if forgets to check that).
If it doesn't find it, it picks clang instead.
I found that this fixes that ugly behavior:
```
ln -s clang /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/gcc
gcc
rm /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/gcc
```
Then, strangely gcc is fixed...
do you thing I should do that  in the script?

**Comment by mietek** [comment]
I’m experiencing this issue. It seems that I must leave the symlink in place…

**Comment by devernay** [comment]
@mietek did you execute gcc (or /usr/bin/gcc) before removing the link?

**Comment by mietek** [comment]
Yes, that’s what I mean. It didn’t help.

**Comment by devernay** [comment]
You're right. I'll leave the link there, then, which replicates Xcode's default behavior (i.e. gcc launches clang)

**Comment by devernay** [comment]
fixed in https://github.com/devernay/xcodelegacy/commit/2b8d399cda80e948d108b509219ccb36caf1489d
