### ISSUE TITLE
buildpackages yields error message

### ISSUE THREAD

**Issue by sstillwell** [devernay/xcodelegacy#20]
Newest XcodeLegacy.sh generates a few errors when doing 'buildpackages' on the same source media as worked with earlier versions of the script.  Errors are as follows:

*** Created Xcode3gcc42.tar.gz in directory /Users/scott/XcodeUpdates
*** Created Xcode3llvmgcc42.tar.gz in directory /Users/scott/XcodeUpdates
patching file hashtable
Hunk #2 FAILED at 1042.
Hunk #3 succeeded at 1217 with fuzz 1.
1 out of 3 hunks FAILED -- saving rejects to file hashtable.rej
*** Created Xcode104SDK.tar.gz in directory /Users/scott/XcodeUpdates
patching file hashtable
Hunk #2 FAILED at 1042.
Hunk #3 succeeded at 1217 with fuzz 1.
1 out of 3 hunks FAILED -- saving rejects to file hashtable.rej
*** Created Xcode105SDK.tar.gz in directory /Users/scott/XcodeUpdates
*** Created Xcode106SDK.tar.gz in directory /Users/scott/XcodeUpdates
"disk2" unmounted.
"disk2" ejected.

Running 'install' afterwards does not generate any errors, but I'm not sure what problems may be hiding under the surface.

**Comment by devernay** [comment]
Nothing bad here, the script just fixes a known bug in the hashtable include file. I don't understand why the patch fails, buti'll try to find out.

**Comment by sstillwell** [comment]
Thanks.  If there's any additional information I can provide, just let me know.

**Comment by devernay** [comment]
script was borked during a previous commit, fixing this in next commit
