### ISSUE TITLE
Integrate with https://github.com/phracker/MacOSX-SDKs

### ISSUE THREAD

**Issue by ddobrev** [devernay/xcodelegacy#24]
The linked project has the SDK-s already extracted so your script could use them instead of downloading the entire old Xcode-s.

**Comment by devernay** [comment]
unfortunately, redistributing SDKs infringes the Xcode licence.

**Comment by devernay** [comment]
unfortunately, redistributing SDKs infringes the Xcode licence, specifically this part
"You agree not to rent, lease, lend, upload to or host on 
any website or server, sell, **redistribute**, or sublicense the Apple Software and Apple Services, in 
whole or in part, or to enable others to do so."
ref: http://images.apple.com/legal/sla/docs/xcode.pdf
