### ISSUE TITLE
Add selection of SDK-s to install

### ISSUE THREAD

**Issue by ddobrev** [devernay/xcodelegacy#25]
Downloading everything is very slow, especially if one does not need all of the SDK-s.

**Comment by devernay** [comment]
I have no time to work on this. Downloading everything has to be done only once, this is no big deal for me. Feel free tu submit a pull request with a solution.

**Comment by devernay** [comment]
@ddobrev can you please test if the new options work for you?

**Comment by ddobrev** [comment]
Thank you for these options. I am going to test in no more than an hour.

**Comment by ddobrev** [comment]
Works for me.

**Comment by toonetown** [comment]
Are you planning on issuing an update with these changes (version 1.8, I'm guessing)?

**Comment by devernay** [comment]
done! https://github.com/devernay/xcodelegacy/releases/tag/v1.8
