### ISSUE TITLE
Add download links which do not require an Apple Developer account

### ISSUE THREAD

**Issue by ddobrev** [devernay/xcodelegacy#26]
The download links you provided only work with the (paid) Apple Developer account. There are alternative links to Apple's download site which really require only signing in with an Apple ID. Most of them can be taken from http://stackoverflow.com/a/10335943 . There are a few missing - for installing on older versions of OS X - but those can be found too with a little effort.

**Comment by devernay** [comment]
These used to work when login in with an apple ID. Apple just changed that and may change that in the future too...
