### ISSUE TITLE
ld issue for ppc compiler

### ISSUE THREAD

**Issue by 51test2003** [devernay/xcodelegacy#27]
Could not compiler the ppc target with these components.

Steps:
1. Make a fresh project with Xcode 7.3.1.
2.Set the Base SDK to Mac OS X 10.5
3.Set the Compiler to GCC 4.2
4.Set the Deploy target to OS X 10.5
5.Compiler

Result:

Ld DerivedData/test/Build/Products/Debug/test.app/Contents/MacOS/test normal ppc
cd /Users/xxx/Desktop/test
export MACOSX_DEPLOYMENT_TARGET=10.5
/Applications/Xcode.app/Contents/Developer/usr/bin/gcc-4.0 -arch ppc -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.5.sdk -L/Users/xxx/Desktop/test/DerivedData/test/Build/Products/Debug -F/Users/xxx/Desktop/test/DerivedData/test/Build/Products/Debug -filelist /Users/xxx/Desktop/test/DerivedData/test/Build/Intermediates/test.build/Debug/test.build/Objects-normal/ppc/test.LinkFileList -Xlinker -rpath -Xlinker @executable_path/../Frameworks -mmacosx-version-min=10.5 -Xlinker -no_deduplicate -fobjc-link-runtime -framework Cocoa -Xlinker -dependency_info -Xlinker /Users/xxx/Desktop/test/DerivedData/test/Build/Intermediates/test.build/Debug/test.build/Objects-normal/ppc/test_dependency_info.dat -o /Users/xxx/Desktop/test/DerivedData/test/Build/Products/Debug/test.app/Contents/MacOS/test

Running ld for ppc ...
ld: unknown option: -no_deduplicate
collect2: ld returned 1 exit status
Command /Applications/Xcode.app/Contents/Developer/usr/bin/gcc-4.0 failed with exit code 1

**Comment by devernay** [comment]
That's an Xcode 7.3 issue. There does not seem to be any way to disable this flag.
You could copy-paste the command-line to a terminal and remove the flags "-Xlinker -no_deduplicate".
Or you could use another build system than Xcode (Makefile, cmake, qmake...).

see also https://forums.developer.apple.com/thread/44905

**Comment by 51test2003** [comment]
I fixed the compiler issue. Add a User-Defined build setting
LD_DONT_RUN_DEDUPLICATION and set its value to NO.

Everything goes right.:)

**Comment by devernay** [comment]
Thanks for finding out, i'll put that un thé readme/faq
Le 17 août 2016 4:29 AM, 51test2003 <notifications@github.com> a écrit :I fixed the compiler issue. Add a User-Defined build setting
LD_DONT_RUN_DEDUPLICATION and set its value to NO.

Everything goes right.:)

**Comment by chobits** [comment]
> Le 17 août 2016 4:29 AM, 51test2003 notifications@github.com a écrit :I fixed the compiler issue. Add a User-Defined build setting LD_DONT_RUN_DEDUPLICATION and set its value to NO.

hi @devernay, how do u fix this issue?

**Comment by devernay** [comment]
xcodelegacy now installs a ld stub which filters the unsupported arguments, so it should rune fine out of the box. see: https://github.com/devernay/xcodelegacy/blob/master/XcodeLegacy.sh#L746

**Comment by chobits** [comment]
> xcodelegacy now installs a ld stub which filters the unsupported arguments, so it should rune fine out of the box. see: https://github.com/devernay/xcodelegacy/blob/master/XcodeLegacy.sh#L746

thanks!
