### ISSUE TITLE
Cant install 10.10 sdk from gz

### ISSUE THREAD

**Issue by CirrusThink** [devernay/xcodelegacy#29]
I have manually added to my computer the Xcode1010SDK folder in the same directory where the legacy script lives. I also added in same directory the .gz folder 
I get the following issue notice the gz.gz

 sudo ./XcodeLegacy.sh -osx1010 install
**\* Info: found Xcode >= 4.3
gzip: can't stat: Xcode1010SDK.tar.gz (Xcode1010SDK.tar.gz.gz): No such file or directory
**\* installed Xcode1010SDK.tar.gz
touch: /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.10.sdk/legacy: No such file or directory
**\* Not modifying MacOSX Info.plist (found original at /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Info.plist-original, uninstall first to force install)

**Comment by devernay** [comment]
did you follow the procedure (build packages using the "buildpackages" option)?
