### ISSUE TITLE
After installing packages with latest XcodeLegacy, GNU Ada fails to build projects using gprbuild

### ISSUE THREAD

**Issue by sstillwell** [devernay/xcodelegacy#33]
After installing using latest XcodeLegacy onto Xcode 8.3.2, trying to compile an Ada program using either command-line 'gprbuild' or GUI gps (GNAT Programming Studio), get the following:

Error: cannot find as for x86_64 in /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../../../as/x86_64
gprbuild: *** compilation phase failed

If I use XcodeLegacy to uninstall packages and revert back to stock Xcode, the Ada project compiles.

Not sure this is an issue with XcodeLegacy, but I can't find any related messages regarding GNAT either.

**Comment by Harinlen** [comment]
Facing the same problem as well. It should be a bug of XCodeLegacy.

**Comment by mbendiksen** [comment]
Same problem here. Anyone have a workaround?

**Comment by devernay** [comment]
can you test with the current (github) version?

**Comment by sstillwell** [comment]
I’ll try later today. I need to reinstall GNAT first.

**Comment by mbendiksen** [comment]
The problem I saw, which was the same error as above but when trying to compile a different app (not Ada) was solved once I got the current github version. I had previously been using the latest tagged release (2.0).

**Comment by sstillwell** [comment]
I’m afraid it doesn’t fix the issue.

Process:

using existing XcodeLegacy.sh, run
`sudo ./XcodeLegacy.sh uninstall`

Download and replace XcodeLegacy.sh with latest from github.

reinstall SDKs and tools with
`sudo ./XcodeLegacy.sh install`

test gps (GNAT Programming Studio) and gprbuild (command-line build) using latest GPL version of Adacore GNAT (2017 version).

Receive the following:

➜  tutorial gprbuild sdc.gpr
Compile
   [ada]          sdc.adb
Error: cannot find as for x86_64 in /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../../../as/x86_64 or /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../../../../../libexec/as/x86_64 or /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../../../../../../../usr/libexec/as/x86_64
gprbuild: *** compilation phase failed

remove XcodeLegacy SDKs and tools
`sudo ./XcodeLegacy.sh uninstall`

Re-test gprbuild, succeeds.

➜  tutorial gprbuild sdc.gpr
Compile
   [ada]          sdc.adb
   [ada]          except.ads
   [ada]          screen_output.adb
   [ada]          stack.adb
   [ada]          tokens.adb
   [ada]          input.adb
   [ada]          values.adb
   [ada]          instructions.adb
   [ada]          values-operations.adb
Bind
   [gprbind]      sdc.bexch
   [Ada]          sdc.ali
Link
   [link]         sdc.adb

**Comment by devernay** [comment]
@sstillwell  I just commited a quick fix, can you try again?

**Comment by devernay** [comment]
can you please try again?

**Comment by sstillwell** [comment]
Hallelujah!  Success!

➜  tutorial gprbuild sdc.gpr -f
Compile
   [ada]          sdc.adb
   [ada]          except.ads
   [ada]          screen_output.adb
   [ada]          stack.adb
   [ada]          tokens.adb
   [ada]          input.adb
   [ada]          values.adb
   [ada]          instructions.adb
   [ada]          values-operations.adb
Bind
   [gprbind]      sdc.bexch
   [Ada]          sdc.ali
Link
   [link]         sdc.adb

**Comment by devernay** [comment]
fixed in XcodeLegacy 2.1
