### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by Juesto** [devernay/xcodelegacy#45]
For some reason some script functions do not appear to take effect? trying to compile tiger with gcc 4.2 complains it is not supported.
Whoops, looks like I missed the extra files on the repository but, still... 

Additionally for some reason i am getting sdk not found in xcode when `$(DEVELOPER_SDK_DIR)/MacOSX10.4u.sdk` is specified.
Latest Snow Leopard SDK appears to be shipped in Xcode 4.3.3 for Lion (and perhaps this applies to snow leopard version too, i assume)

PS: for some reason it's unable to link because some files do not appear to exist on the linking directory!?

PS: May I email or chat you?

**Comment by devernay** [comment]
Everything is in the script. You have to download the right code version for each SDK. The script patches the 10.4 SDK. I cannot help me, sorry

**Comment by Juesto** [comment]
the script does not appear to download SDKs on its own, i've downloaded them from the other github repo. also, again, the SL sdk extracted is not the newest.
