### ISSUE TITLE
Option to provide the app path

### ISSUE THREAD

**Issue by maxime-viargues-serato** [devernay/xcodelegacy#50]
Hi there,

I am in a case where I need to have both Xcode 7 and 8 installed on the same machine, but the XcodeLegacy script installs in Xcode.app by default. Mine are called Xcode7.app and Xcode8.app, and I need to automate that installation so it's not easy to rename them.
Would it be possible to have an extra argument with the app to target instead of using the default one? e.g.
`sudo ./XcodeLegacy.sh -osx1012 install --path /Applications/Xcode7.app`

Regards,
Maxime

**Comment by maxime-viargues-serato** [comment]
I create a PR that wasn't too hard actually https://github.com/devernay/xcodelegacy/pull/51

**Comment by devernay** [comment]
fixed by #51
