### ISSUE TITLE
Unable to extract 10.12SDK from Xcode8.3.3.xip

### ISSUE THREAD

**Issue by nicolas-cellier-aka-nice** [devernay/xcodelegacy#56]
It seems that it's too late:

    $ pkgutil --verbose --check-signature ./Xcode8.3.3.xip 

> Package "Xcode8.3.3.xip":
>    Status: signed by a certificate that has since expired
>    Certificate Chain:
>     1. Software Update
>        SHA1 fingerprint: 1E 34 E3 91 C6 44 37 DD 24 BE 57 B1 66 7B 2F DA 09 76 E1 FD
>        -----------------------------------------------------------------------------
>     2. Apple Software Update Certification Authority
>        SHA1 fingerprint: FA 02 79 0F CE 9D 93 00 89 C8 C2 51 0B BC 50 B4 85 8E 6F BF
>        -----------------------------------------------------------------------------
>     3. Apple Root CA
>        SHA1 fingerprint: 61 1E 5B 66 2C 59 3A 08 FF 58 D1 4A E2 24 52 D1 98 DF 6C 60
> 

I'm stuck... Any idea to workaround?

**Comment by nicolas-cellier-aka-nice** [comment]
I had to change the date, but this gets really irritating

**Comment by EricFromCanada** [comment]
Apple's software update certificate expired on 2019-10-24, so you need to re-download all your copies of Xcode, which have been re-signed with a new certificate that expires in 2029.

**Comment by devernay** [comment]
fixed
