### ISSUE TITLE
Is it possible to add a Xcode 3.2 from 10.6 PPC?

### ISSUE THREAD

**Issue by barracuda156** [devernay/xcodelegacy#62]
There exists a developer version of 10.6 for PowerPC, and it has working Xcode 3.2. I am interested to compile some software for it like Rstudio and Stan, however I have only managed to get R 4.1.1 built on it (with multiple tweaks to bypass dependency on gcc11), and there it stuck, some components still need gcc11.
I have come across the post that advises XcodeLegacy to build a cross-compiler on Intel Mac to be used for building software for PowerPC: http://maniacsvault.net/articles/powerpccross

Now, the issue is that no commonly available releases of Xcode support 10.6 PPC. The needed version is bundled with 10A96 and 10A109 builds, which can be downloaded here: https://macintoshgarden.org/apps/mac-os-x-snow-leopard-powerpc-the-early-106-developer-builds
More info on 10.6 PPC here: https://forums.macrumors.com/threads/snow-leopard-on-unsupported-ppc-machines.2232031/

Will it be possible to add this option to the script in order to extract needed components from this specific Xcode and install in Xcode 12?

**Comment by devernay** [comment]
Feel free to contribute it. But I would honestly not use Xcode 12 to build PPC binaries. You may be more lucky using the command-line tools, and it will work better if the host can execute the produced binaries.
Binaries produced for Leopard (10.5) with the PPC architecture will probably run fine on your 10.6 PPC OS (which is not even official), so this is what I would recomment:
- compile on 10.6 intel host
- target 10.5 PPC
