### ISSUE TITLE
PPC architecture and old SDKs are unavailable in Xcode 12.4 GUI

### ISSUE THREAD

**Issue by barracuda156** [devernay/xcodelegacy#63]
The script extracted and installed components into Xcode 12.4 on Catalina (apparently successfully), however they do not appear as available options in Project settings in Xcode GUI.

**Comment by devernay** [comment]
Recent xcode versions probably don't support poroducing PPC code. It was working with Xcode 5, but I would recommend using Xcode 3 or 4 on Snow Leopard.

**Comment by barracuda156** [comment]
I have Catalina with Xcode 12.4 on an Intel machine and 10.6 PPC with Xcode
3.2 PPC on a PowerPC one.
My intent was to use Intel machine to cross-compile for 10.6 PPC.
