### ISSUE TITLE
as and ld Intel-only in ppc and ppc64 libexec?

### ISSUE THREAD

**Issue by barracuda156** [devernay/xcodelegacy#64]
I am sorry if I get this wrong, but as and ld files that are installed into /Applications/Xcode.app/Contents/Developer/usr/libexec/gcc/darwin/ppc and /Applications/Xcode.app/Contents/Developer/usr/libexec/gcc/darwin/ppc64 both contain only x86_64 and i386 architectures. Shouldn't they be for ppc and ppc64 instead?

I have used the script in its default form (complete install) on MacOS Catalina with Xcode 12.4.

**Comment by barracuda156** [comment]
At the same time on a PowerPC installation of Xcode as files have ppc arch:

36-137:~ svacchanda$ file /Developer/usr/libexec/gcc/darwin/ppc64/as 
/Developer/usr/libexec/gcc/darwin/ppc64/as: Mach-O universal binary with 3 architectures
/Developer/usr/libexec/gcc/darwin/ppc64/as (for architecture i386):	Mach-O executable i386
/Developer/usr/libexec/gcc/darwin/ppc64/as (for architecture ppc7400):	Mach-O executable ppc
/Developer/usr/libexec/gcc/darwin/ppc64/as (for architecture x86_64):	Mach-O 64-bit executable x86_64
36-137:~ svacchanda$ file /Developer/usr/libexec/gcc/darwin/ppc/as 
/Developer/usr/libexec/gcc/darwin/ppc/as: Mach-O universal binary with 3 architectures
/Developer/usr/libexec/gcc/darwin/ppc/as (for architecture i386):	Mach-O executable i386
/Developer/usr/libexec/gcc/darwin/ppc/as (for architecture ppc7400):	Mach-O executable ppc
/Developer/usr/libexec/gcc/darwin/ppc/as (for architecture x86_64):	Mach-O 64-bit executable x86_64
36-137:~ svacchanda$

**Comment by devernay** [comment]
the linker and assembler have to be executable on the host (Catalina is x86_64 only), but they may still be able to assemble and link ppc binaries.
I would highly recommend building ppc binaries on a on that can execute them (Mac OS X 10.6 Snow Leopard or older)
