### ISSUE TITLE
Safe for use with XCode 6.1.1?

### ISSUE THREAD

**Issue by DrLou** [devernay/xcodelegacy#9]
Have just tried against 6.1.1, and am seeing lots of:

Running ld for i386 ...
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ld-original: fork: Resource temporarily unavailable
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ld-original: line 37: Running: command not found
....
clang: error: unable to execute command: No such file or directory
clang: error: linker command failed due to signal (use -v to see invocation)

Granted, may have nothing to do with the xcodelegacy installs, but thought we should run it by you!

**Comment by melomac** [comment]
Having the same issue here:

    Running ld for x86_64 .../Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ld-original: fork: Resource temporarily unavailable
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ld-original: line 37: Running: command not found
    (...)
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ld: line 37: Running: command not found
    collect2: ld returned 127 exit status
    
    Command /Applications/Xcode.app/Contents/Developer/usr/bin/gcc-4.2 failed with exit code 1

**Comment by devernay** [comment]
can you please post the output of:
`ls -l /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ld*`
I suspect that the script was run twice and erased the original `ld` binary. In this case, I can add a check for this.
